#!/bin/bash
#
#EXTENTS="x86Os x86 x86mmxOs x86mmx k6p3 k7p4 k8p5 k9c2 atom coreix k10 "
 #/bin/busybox tar -cvk --owner=root --format=pax  busybox-k5 busybox-x86mmx busybox-k6 busybox-k6p3 busybox-k7 busybox-k7p4 busybox-k8 busybox-k8p5 busybox-k9 busybox-k9c2 busybox-atom busybox-k10 busybox-coreix busybox-debug > bb.tar 
 ./busybox-k8p5 tar -cvk  busybox-k5 busybox-x86mmx busybox-k6 busybox-k6p3 busybox-k7 busybox-k7p4 busybox-k8 busybox-k8p5 busybox-k9 busybox-k9c2 busybox-atom busybox-k10 busybox-coreix busybox-debug > bb.tar 
  [ $? -ne 0 ] && exit $?
  xz -zvfk9 bb.tar
exit 0
#

