#!/bin/bash
#
#EXTENTS="x86Os x86 x86mmxOs x86mmx k6p3 k7p4 k8p5 k9c2 atom coreix k10 "
 tar -cvk -b4 --owner=root --format=pax busybox-k5 busybox-x86mmx busybox-k6 busybox-k6p3 busybox-k7 busybox-k7p4 busybox-k8 busybox-k8p5 busybox-k9 busybox-k9c2 busybox-atom busybox-k10 busybox-coreix busybox-debug > bb.tar 
  [ $? -ne 0 ] && exit $?
  lrzip -kfvv -p 1 -T -w 8 -N 0  -L 8  bb.tar  
  [ $? -ne 0 ] && exit $?
exit 0
#

