#!/bin/busybox ash
#set -x
NUMSTR=""
usage()
{
  echo "$0 : Tool to set the links to programs of the actual toolchain"
  echo " -->  make your updates for gcc, binutils, glibc effective by setting "
  echo "      the necessary symlinks for toolchain"
  echo "usage:"
  echo "toolchain <suffix version of gcc binaries> <suffix version of binutils binaries> <suffix version of libc> "
  echo ""
  echo "you must specify at least the folders"
  echo "outputfile defaults to 'mkdiffs_from_\$subfolder1_\$subfolder2.txt'"
  exit 0
}

ARG=""
ARG="$1 $2 $3"
if [ "$1" = "" ]; then
  usage
fi
GCCVER="$1"
BINGASVER="$2"
LIBCVER="$3"
RC=9999
GCCBINDIR=/usr/bin
GASBINDIR=/usr/bin
if [ "$GCCVER" != "" ]; then
  GCCBINS=`/bin/busybox find $GCCBINDIR/  -name "*-$GCCVER" 2>/dev/null`
  bin=""
  lbin=""
  for bin in $GCCBINS; do
     #lbin=`/bin/busybox basename $bin 2>/dev/null`
     lbin=${bin%-*}
     [ "$lbin" != "" ] &&  /bin/busybox ln -sf "$bin" "$lbin" 2>/dev/null
     RC=$?
     echo "symlinked  $bin to $lbin with '$RC'"
     case `/bin/busybox basename $lbin 2>/dev/null` in
	     gcc)
           /bin/busybox ln -sf "$bin" "$GCCBINDIR/cc" 2>/dev/null
	       RC=$?
	       echo "symlinked  $bin to $GCCBINDIR/cc with '$RC'"
         ;;
	     g++)
           /bin/busybox ln -sf "$bin" "$GCCBINDIR/cxx" 2>/dev/null
           RC=$?
	       echo "symlinked  $bin to $GCCBINDIR/cxx with '$RC'"
           /bin/busybox ln -sf "$bin" "$GCCBINDIR/c++" 2>/dev/null
           RC=$?
	       echo "symlinked  $bin to $GCCBINDIR/c++ with '$RC'"
	     ;;
     esac
  done
fi
if [ "$BINGASVER" != "" ]; then
  GASBINS=`/bin/busybox find $GASBINDIR/  -name "*-$BINGASVER" 2>/dev/null`
  bin=""
  lbin=""
  for bin in $GASBINS; do
     # cut the suffix version number to obtain the symlink name
     lbin=${bin%-*}
     [ "$lbin" != "" ] && /bin/busybox ln -sf "$bin" "$lbin" 2>/dev/null
     RC=$?
  done  
fi
if [ "$LIBCVER" != "" ]; then
  :  # TODO!!
fi

exit $RC
#
